# Generated by Django 3.2.4 on 2021-06-26 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='photo')),
                ('video', models.FileField(upload_to='video')),
                ('is_published', models.BooleanField(default=True)),
                ('video_date', models.DateTimeField(default=datetime.datetime.now)),
                
            ],
        ),
    ]
